### ISSUE TITLE
Wux Weapp 交流群

### ISSUE THREAD

**Issue by skyvow** [wux-weapp/wux-weapp#196]
<img width="640" alt="wechat-helper" src="https://user-images.githubusercontent.com/14972920/51423307-184cbe00-1bf9-11e9-8adb-b4a56c9fb88d.png">

**Comment by erxiaoyu** [comment]
如何修改样式？

**Comment by zhanjian1514** [comment]
我使用Icon出错了，报500，找不到图标，.tff文件

**Comment by controller-shine** [comment]
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:513:3)
    at Object.readSync (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\js\libs\vseditor\bundled\editor.bundled.js:2:5669360)
    at tryReadSync (fs.js:338:20)
    at Object.readFileSync (fs.js:375:19)
    at Object.s.readFileSync (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\js\unpack\hackrequire\index.js:1:1216)
    at FileUtils.getFile (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\8e2026561e71ea67df211489b756510c.js:597:41)
    at o (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\81a45c52b8b2dedcaa34d05c772d10f0.js:1:1199)
    at async Proxy.exports.default (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\81a45c52b8b2dedcaa34d05c772d10f0.js:1:2423)
    at async Proxy.exports.compileMiniProgramJS (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\d7959893394997a84922a4171f531a12.js:1:221)
    at async Proxy.module.exports (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\87c0ac209c25d8bb448550638bb17663.js:1:988)

**Comment by wuyu3163** [comment]
DatePicker 日期选择器,点击后，如何设置默认为当前日期。

**Comment by 1075488066** [comment]
文档的导包和实际使用完全对不上。
