### ISSUE TITLE
关于Picker选择器使用defaultFieldNames自定义options中label后二次弹窗显示空白问题

### ISSUE THREAD

**Issue by CharryLi** [wux-weapp/wux-weapp#352]
![image](https://user-images.githubusercontent.com/3435111/70991174-ef32f700-2101-11ea-85ca-f5f9b5888562.png)
![image](https://user-images.githubusercontent.com/3435111/70991417-5fda1380-2102-11ea-869f-3bee2f64edb7.png)
![image](https://user-images.githubusercontent.com/3435111/70991453-6f595c80-2102-11ea-9ecf-1e89138f6bf8.png)
Picker控件在使用defaultFieldNames自定义options中label后，首次点击弹出可以正常显示选项内容，点击确定按钮选值后，再次点击弹出控件时，选项空白，然后在选项位置上下滑动几下，选项又显示了，之后就一直这样，之后测试了去掉defaultFieldNames后正常。

**Comment by controller-shine** [comment]
EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:513:3)
    at Object.readSync (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\js\libs\vseditor\bundled\editor.bundled.js:2:5669360)
    at tryReadSync (fs.js:338:20)
    at Object.readFileSync (fs.js:375:19)
    at Object.s.readFileSync (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\js\unpack\hackrequire\index.js:1:1216)
    at FileUtils.getFile (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\8e2026561e71ea67df211489b756510c.js:597:41)
    at o (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\81a45c52b8b2dedcaa34d05c772d10f0.js:1:1199)
    at async Proxy.exports.default (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\81a45c52b8b2dedcaa34d05c772d10f0.js:1:2423)
    at async Proxy.exports.compileMiniProgramJS (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\d7959893394997a84922a4171f531a12.js:1:221)
    at async Proxy.module.exports (C:\Users\Administrator\AppData\Local\微信开发者工具\User Data\WeappCode\package.nw\core.wxvpkg\87c0ac209c25d8bb448550638bb17663.js:1:988)

**Comment by controller-shine** [comment]
为什么我导入会出现这样的情况，怎么解决
