### ISSUE TITLE
wux-date-picker BUG太多了

### ISSUE THREAD

**Issue by qhl100** [wux-weapp/wux-weapp#360]
bug1:wux-date-picker 默认minDate日期不是2000-01-01 00:00:00 而是2000-02-01 00:00:00，
bug2:弹出的日期picker 不选择，直接点确认报错：
VM3833:1 thirdScriptError
Cannot read property '0' of null; [Component] Event Handler Error @ components/date-picker/index#onConfirm
TypeError: Cannot read property '0' of null
    at http://127.0.0.1:43202/appservice/components/picker-view/utils.js:59:60
    at Array.reduce (<anonymous>)
    at getRealValues (http://127.0.0.1:43202/appservice/components/picker-view/utils.js:58:118)
    at be.getValue (http://127.0.0.1:43202/appservice/components/multi-picker-view/index.js:47:40)
    at be.getValue (http://127.0.0.1:43202/appservice/components/date-picker-view/index.js:217:176)
    at be.getPickerValue (http://127.0.0.1:43202/appservice/components/helpers/popupMixin.js:63:169)
    at be.close (http://127.0.0.1:43202/appservice/components/helpers/popupMixin.js:46:24)
    at be.onConfirm (http://127.0.0.1:43202/appservice/components/helpers/popupMixin.js:51:27)
    at Object.r.safeCallback (http://127.0.0.1:43202/appservice/__dev__/WAService.js:2:1376950)
    at http://127.0.0.1:43202/appservice/__dev__/WAService.js:2:1554900
console.error @ VM3833:1
errorReport @ VM3849 WAService.js:2
thirdErrorReport @ VM3849 WAService.js:2
(anonymous) @ VM3849 WAService.js:2
(anonymous) @ VM3849 WAService.js:2
r.safeCallback @ VM3849 WAService.js:2
r.call @ VM3849 WAService.js:2
message @ VM3849 WAService.js:2
r.safeCallback @ VM3849 WAService.js:2
(anonymous) @ VM3849 WAService.js:2
r @ VM3849 WAService.js:2
(anonymous) @ VM3849 WAService.js:2
(anonymous) @ VM3849 WAService.js:2
n @ VM3847 asdebug.js:1
(anonymous) @ VM3847 asdebug.js:1
(anonymous) @ VM3847 asdebug.js:1
_ws.onmessage @ VM3847 asdebug.js:1

**Comment by skyvow** [comment]
@qhl100 未复现

**Comment by dibadibadiudiu** [comment]
这个是真的啊，我也出现了

**Comment by dibadibadiudiu** [comment]
这个是真的啊，我也出现了 @skyvow

**Comment by dibadibadiudiu** [comment]
你看看你PICKER的演示视频 就复现了 初始日期是2000-02-01 00:00:00

**Comment by skyvow** [comment]
@dibadibadiudiu 又看了遍代码，默认值是 2000-02-01，文档可能有误
