### ISSUE TITLE
使用下拉加载，停止加载更多，显示没有更多数据报错

### ISSUE THREAD

**Issue by wangben5** [wux-weapp/wux-weapp#373]
使用这个报错
       $stopWuxLoader('#wux-refresher', this, true)
报错如下
VM10411:1 thirdScriptError
(intermediate value)(intermediate value)(intermediate value).selectComponent is not a function;at api request success callback function
TypeError: (intermediate value)(intermediate value)(intermediate value).selectComponent is not a function
    at getCtx (http://127.0.0.1:10637/appservice/miniprogram_npm/wux-weapp/index.js:10:104)
    at $stopWuxLoader (http://127.0.0.1:10637/appservice/miniprogram_npm/wux-weapp/index.js:34:52)
    at Object.success (http://127.0.0.1:10637/appservice/pages/friends/friends.js:177:39)
    at success (http://127.0.0.1:10637/appservice/utils/http.js:29:15)
    at Function.o.(anonymous function) (http://127.0.0.1:10637/appservice/__dev__/WAService.js:2:1497871)
    at http://127.0.0.1:10637/appservice/__dev__/WAService.js:2:128035
    at E (http://127.0.0.1:10637/appservice/__dev__/WAService.js:2:560801)
    at i.<anonymous> (http://127.0.0.1:10637/appservice/__dev__/WAService.js:2:988158)
    at i.emit (http://127.0.0.1:10637/appservice/__dev__/WAService.js:2:615013)
    at Ii (http://127.0.0.1:10637/appservice/__dev__/WAService.js:2:989020)

**Comment by skyvow** [comment]
@wangben5 信息提供不足，无法复现
